stages:
  - build
  - deploy_gcp

build_images:
  stage: build
  image: docker:20.10.16

  services:
    - docker:20.10.16-dind

  variables:
    DOCKER_TLS_CERTDIR: '/certs'

  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS

  script:
    - docker build -t costabeto/k8s-ci-cd-example app/.
    - docker push costabeto/k8s-ci-cd-example

deploy_gcp:
  stage: deploy_gcp

  before_script:
    - chmod 400 $SSH_KEY

  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY gcp@$SSH_SERVER "sudo rm -Rf ./k8s-ci-cd-example/ && sudo git clone https://gitlab.com/costabeto/k8s-ci-cd-example.git && cd k8s-ci-cd-example && sudo chmod +x ./setup.sh && ./setup.sh"
